name = "public-knowledge-mcp-server"
main = "dist/fixed-mcp-worker.js"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "KNOWLEDGE_BASE_KV"
id = "4d889b198acc48e59d7a1daf8d285a7c"
preview_id = "6217aa250e4d44de97e913458a24acef"

[vars]
ENVIRONMENT = "production"
